/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivIDInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "computeAccessFlagsEnc"
      | "getAccessFlagsEnc"
      | "getMyAttributes"
      | "getMyLastFlagsEnc"
      | "hasData"
      | "isAdultEnc"
      | "isInRegionEnc"
      | "isKycPassedEnc"
      | "protocolId"
      | "submitAttributes"
      | "updateAttributes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeAccessFlagsEnc",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessFlagsEnc",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyAttributes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyLastFlagsEnc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdultEnc",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInRegionEnc",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKycPassedEnc",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitAttributes",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAttributes",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeAccessFlagsEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessFlagsEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyLastFlagsEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdultEnc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInRegionEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKycPassedEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAttributes",
    data: BytesLike
  ): Result;
}

export interface PrivID extends BaseContract {
  connect(runner?: ContractRunner | null): PrivID;
  waitForDeployment(): Promise<this>;

  interface: PrivIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeAccessFlagsEnc: TypedContractMethod<
    [allowedRegionHandle: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getAccessFlagsEnc: TypedContractMethod<
    [user: AddressLike, allowedRegionHandle: BytesLike, proof: BytesLike],
    [[string, string] & { accessA: string; accessB: string }],
    "nonpayable"
  >;

  getMyAttributes: TypedContractMethod<[], [[string, string, string]], "view">;

  getMyLastFlagsEnc: TypedContractMethod<
    [],
    [[string, string] & { accessA: string; accessB: string }],
    "view"
  >;

  hasData: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isAdultEnc: TypedContractMethod<[user: AddressLike], [string], "nonpayable">;

  isInRegionEnc: TypedContractMethod<
    [user: AddressLike, regionHandle: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;

  isKycPassedEnc: TypedContractMethod<[user: AddressLike], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitAttributes: TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateAttributes: TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeAccessFlagsEnc"
  ): TypedContractMethod<
    [allowedRegionHandle: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAccessFlagsEnc"
  ): TypedContractMethod<
    [user: AddressLike, allowedRegionHandle: BytesLike, proof: BytesLike],
    [[string, string] & { accessA: string; accessB: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMyAttributes"
  ): TypedContractMethod<[], [[string, string, string]], "view">;
  getFunction(
    nameOrSignature: "getMyLastFlagsEnc"
  ): TypedContractMethod<
    [],
    [[string, string] & { accessA: string; accessB: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasData"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAdultEnc"
  ): TypedContractMethod<[user: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "isInRegionEnc"
  ): TypedContractMethod<
    [user: AddressLike, regionHandle: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isKycPassedEnc"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitAttributes"
  ): TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAttributes"
  ): TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
