name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Determine basePath from repository
        shell: bash
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          if [[ "$REPO" == "${OWNER}.github.io" ]]; then
            echo "NEXT_BASE_PATH=" >> "$GITHUB_ENV"
          else
            echo "NEXT_BASE_PATH=/$REPO" >> "$GITHUB_ENV"
          fi
          echo "NEXT_BASE_PATH=${NEXT_BASE_PATH}"

      - name: Install dependencies (workspaces)
        run: npm ci

      - name: Build static site
        working-directory: frontend
        env:
          NEXT_BASE_PATH: ${{ env.NEXT_BASE_PATH }}
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      - name: Prepare Pages artifact
        shell: bash
        working-directory: frontend
        run: |
          mkdir -p out
          touch out/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


